### ISSUE TITLE
Traceback when running ssci from script

### ISSUE THREAD

**Issue by kellerkind** [NaohiroTamura/python-scciclient#1]
When running scciclient from script I get this error message. Initilising in python ide is ok. The error from script is:

```
Traceback (most recent call last):
  File "./lom-config.py", line 14, in <module>
    from scciclient.irmc import scci
  File "./linux/bin/python/lib/python2.6/site-packages/scciclient/__init__.py", line 19, in <module>
    'scciclient').version_string()
  File "./linux/bin/python/lib/python2.6/site-packages/pbr/version.py", line 78, in version_string
    for part in self.release_string().split('.'):
  File "./linux/bin/python/lib/python2.6/site-packages/pbr/version.py", line 70, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "./linux/bin/python/lib/python2.6/site-packages/pbr/version.py", line 62, in _get_version_from_pkg_resources
    return packaging.get_version(self.package)
  File "./linux/bin/python/lib/python2.6/site-packages/pbr/packaging.py", line 567, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
```

**Comment by NaohiroTamura** [comment]
Thank you for using python-scciclient.

I haven't tested in python 2.6, but 2.7.
Because openstack ironic supports only python 2.7 at this moment.
Please try to see if tox works or not in your python 2.7 environment first.

naohirot@ubuntu:~/work/src/python-scciclient$ rm -rf .tox/ .testrepository/
naohirot@ubuntu:~/work/src/python-scciclient$ tox
py27 create: /home/naohirot/work/src/python-scciclient/.tox/py27
py27 installdeps: -r/home/naohirot/work/src/python-scciclient/requirements.txt, -r/home/naohirot/work/src/python-scciclient/test-requirements.txt
py27 develop-inst: /home/naohirot/work/src/python-scciclient
py27 runtests: PYTHONHASHSEED='1092867706'
py27 runtests: commands[0] | python setup.py testr --slowest --testr-args=
running testr
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ . --list
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpLRCpnO
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpv3Tdao
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpJnh60p
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpXTVtuL
Ran 25 tests in 0.336s
PASSED (id=0, skips=1)
Slowest Tests
Test id                                                                            Runtime (s)

---

scciclient.tests.irmc.test_scci.SCCITestCase.test_get_report_ok                    0.102
scciclient.tests.irmc.test_scci.SCCITestCase.test_scci_cmd_authentication_failure  0.046
scciclient.tests.irmc.test_scci.SCCITestCase.test_virtual_media_cd_setting_ok      0.045
scciclient.tests.irmc.test_scci.SCCITestCase.test_power_on_http_failed             0.044
scciclient.tests.irmc.test_scci.SCCITestCase.test_get_irmc_version_ng              0.040
scciclient.tests.irmc.test_scci.SCCITestCase.test_mount_cd_ok                      0.039
scciclient.tests.irmc.test_scci.SCCITestCase.test_get_irmc_version_ok              0.037
scciclient.tests.irmc.test_scci.SCCITestCase.test_get_report_http_failed           0.037
scciclient.tests.irmc.test_scci.SCCITestCase.test_httpretty_http_works_ok          0.033
scciclient.tests.irmc.test_scci.SCCITestCase.test_power_reset_ok                   0.033
pep8 create: /home/naohirot/work/src/python-scciclient/.tox/pep8
pep8 installdeps: -r/home/naohirot/work/src/python-scciclient/requirements.txt, -r/home/naohirot/work/src/python-scciclient/test-requirements.txt
pep8 develop-inst: /home/naohirot/work/src/python-scciclient
pep8 runtests: PYTHONHASHSEED='1092867706'
pep8 runtests: commands[0] | flake8
___________________________________ summary ____________________________________
  py27: commands succeeded
  pep8: commands succeeded
  congratulations :)

**Comment by kellerkind** [comment]
Sorry taking a while to get back Python 2.7 installed on RHEL 6 where I want to run the scci scripts.
Tests now passes fine in a 2.7 environment:

```
ERROR:   py34: InterpreterNotFound: python3.4
  py27: commands succeeded
  pep8: commands succeeded
```
